EmployeeData/Controllers/EmployeeDataController.cs
using EmployeeBAL;
using EmployeeDAL;
using EmployeeData.Models;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace EmployeeData.Controllers
{
    public class EmployeeDataController : Controller
    {
        IEmployeeService service = new EmployeeService();
       
        public ActionResult ListEmployee()
        {
            try
            {
                return View(service.GetAllEmployees().ToList());
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "An error occurred. Please contact support.");
                return View("error");
            }
            
        }
        public ActionResult Create()
        {
            try
            {
                EmployeesDetails employeesDetails = new EmployeesDetails();
                var regions = service.GetRegions();
                ViewBag.Regions = new SelectList(regions, "RegionId", "RegionName");

                return View(employeesDetails);
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "An error occurred. Please contact support.");
                return View("error");
            }
            
        }

        [HttpPost]
        public ActionResult Create(EmployeesDetails employees)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    Employee emp = new Employee()
                    {
                        EmpName = employees.EmpName,
                        Designation = string.Join("", employees.Designation),
                        PhoneNo = employees.PhoneNo,
                        Email = employees.Email,
                        RegionId = employees.RegionId,
                        ZoneId = employees.ZoneId,
                        BranchId = employees.BranchId,
                        Gender = employees.Gender,
                        DateOfBirth = employees.DateOfBirth,
                        Address = employees.Address,
                        Technology = string.Join(",", employees.Technology),
                        CreatedOn = DateTime.Now
                    };
                    service.AddEmployees(emp);

                    foreach (var doc in employees.Documents)
                    {
                        var document = new EmpDocument()
                        {
                            DocName = doc.FileName,
                            DocPath = SaveToPhysicalLocation(doc),
                            EmpId = emp.EmpId,
                            CreatedOn = DateTime.Now
                        };
                        service.AddEmployeeDoc(document);
                    }
                    ViewData["Message"] = "Record saved successfully";
                    return RedirectToAction("ListEmployee");
                }
                else
                {
                    ModelState.AddModelError("", "An error occurred. Please contact support.");
                    TempData["Message"] = "Please fill all form field";
                    TempData.Keep();
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred. Please contact support.");
                return View("error");
            }

        }

        public ActionResult GetZones(int regionId)
        {
            try
            {
                var zones = service.GetZoneById(regionId);
                return Json(zones, JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "An error occurred. Please contact support.");
                return View("error");
            }
            
        }

        public ActionResult GetBranches(int zoneId)
        {
            try
            {
                var branches = service.GetBranchById(zoneId);
                return Json(branches, JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "An error occurred. Please contact support.");
                return View("error");
            }
        }

        public ActionResult DownloadDoc(int docId)
        {
            try
            {
                var document = service.GetDocumentById(docId);
                if (document != null)
                {
                    byte[] fileBytes;

                    using (var fileStream = new FileStream(document.DocPath, FileMode.Open, FileAccess.Read))
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            fileStream.CopyTo(memoryStream);
                            fileBytes = memoryStream.ToArray();
                        }
                    }
                    string fileName = document.DocName;
                    return File(fileBytes, "application/octet-stream", fileName);
                }
                else
                {
                    return HttpNotFound();
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "An error occurred. Please contact support.");
                return View("error");
            }
            
        }

        public ActionResult ExportToExcel()
        {
            try
            {
                var employees = service.GetAllEmployees();
                ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
                using (var package = new ExcelPackage())
                {
                    var worksheet = package.Workbook.Worksheets.Add("Employees");

                    worksheet.Cells[1, 1].Value = "ID";
                    worksheet.Cells[1, 2].Value = "Name";
                    worksheet.Cells[1, 3].Value = "Designation";
                    worksheet.Cells[1, 4].Value = "Phone no";
                    worksheet.Cells[1, 5].Value = "Email";
                    worksheet.Cells[1, 6].Value = "Region";
                    worksheet.Cells[1, 7].Value = "Zone";
                    worksheet.Cells[1, 8].Value = "Branch";
                    worksheet.Cells[1, 9].Value = "Gender";
                    worksheet.Cells[1, 10].Value = "DateOfBirth";
                    worksheet.Cells[1, 11].Value = "Address";
                    worksheet.Cells[1, 12].Value = "Technology";


                    int row = 2;
                    foreach (var employee in employees)
                    {
                        worksheet.Cells[row, 1].Value = employee.EmpId;
                        worksheet.Cells[row, 2].Value = employee.EmpName;
                        worksheet.Cells[row, 3].Value = employee.Designation;
                        worksheet.Cells[row, 4].Value = employee.PhoneNo;
                        worksheet.Cells[row, 5].Value = employee.Email;
                        worksheet.Cells[row, 6].Value = employee.Region.RegionName;
                        worksheet.Cells[row, 7].Value = employee.Zone.ZoneName;
                        worksheet.Cells[row, 8].Value = employee.Branch.BranchName;
                        worksheet.Cells[row, 9].Value = employee.Gender;
                        worksheet.Cells[row, 10].Value = employee.DateOfBirth;
                        worksheet.Cells[row, 11].Value = employee.Address;
                        worksheet.Cells[row, 12].Value = employee.Technology;
                        row++;
                    }

                    // Auto-fit columns for better readability
                    worksheet.Cells.AutoFitColumns();

                    // Convert the Excel package to a byte array
                    byte[] fileBytes = package.GetAsByteArray();

                    // Return the Excel file for download
                    return File(fileBytes, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Employees.xlsx");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "An error occurred. Please contact support.");
                return View("error");
            }
            
        }

        private string SaveToPhysicalLocation(HttpPostedFileBase file)
        {
            try
            {
                if (file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/App_Data/"), fileName);
                    file.SaveAs(path);
                    return path;
                }

                return string.Empty;
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "An error occurred. Please contact support.");
                return "Exception occurred";
            }
        }

        public ActionResult Error()
        {
            var err = TempData["Message"];
            ViewBag.Error = err;
            return View("error");
        }
    }
}

EmployeeData/Views/EmployeeData/Create.cshtml
@model EmployeeData.Models.EmployeesDetails

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<h3 class="text-success">@ViewData["Message"]</h3>

@using (Html.BeginForm("Create", "EmployeeData", FormMethod.Post, new { enctype = "multipart/form-data", @id="myform" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>EmployeesDetails</h4>
        <hr />
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.HiddenFor(model => model.EmpId);

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmpName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmpName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Designation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Designation", Enum.GetValues(typeof(EmployeeData.Models.Designations)).Cast<EmployeeData.Models.Designations>().Select(d => new SelectListItem
           {
               Value = d.ToString(),
               Text = d.ToString()
           }),
               "Select Designation", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Designation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control",@id="phoneno" } })
                @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RegionId, (SelectList)ViewBag.Regions, "Select Region", new { id = "regionDropdown" })
                @Html.ValidationMessageFor(model => model.RegionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZoneId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select id="zoneDropdown" name="ZoneId" class="form-control" required>
                    <option>Select Zone</option>
                </select>
                @Html.ValidationMessageFor(model => model.ZoneId, "", new { @class = "text-danger", @id="validateZone" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BranchId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select id="branchDropdown" name="BranchId" class="form-control" required>
                    <option>Select Branch</option>
                </select>
                @Html.ValidationMessageFor(model => model.BranchId, "", new { @class = "text-danger",@id="validateBranch" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control", max = DateTime.Now.ToString("yyyy-MM-dd") } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                Male: @Html.RadioButtonFor(model => model.Gender, "Male", new { htmlAttributes = new { @class = "form-control" } })
                Female: @Html.RadioButtonFor(model => model.Gender, "Female", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Technology, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @foreach (var tech in Enum.GetValues(typeof(EmployeeData.Models.Technologies)))
                {
                    <label>@tech</label>
                    <input type="checkbox" name="Technology" value=@tech />
                }
                @Html.ValidationMessageFor(model => model.Technology, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Documents, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Documents" multiple />
                @Html.ValidationMessageFor(model => model.Documents, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="Apply" value="Create" class="btn btn-default" />

            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListEmployee")
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('#regionDropdown').change(function () {
            var regionId = $(this).val();
            $.getJSON('/EmployeeData/GetZones', { RegionId: regionId }, function (data) {
                var zoneDropdown = $('#zoneDropdown');
                zoneDropdown.empty();
                zoneDropdown.append($('<option>').text('Select Zone'));
                $.each(data, function (index, zone) {
                    zoneDropdown.append($('<option>').text(zone.ZoneName).val(zone.ZoneId));
                });
            });
        });

        $('#zoneDropdown').change(function () {
            var zoneId = $(this).val();
            $.getJSON('/EmployeeData/GetBranches', { zoneId: zoneId }, function (data) {
                var brachDropdown = $('#branchDropdown');
                brachDropdown.empty();
                brachDropdown.append($('<option>').text('Select Branch'));
                $.each(data, function (index, branch) {
                    brachDropdown.append($('<option>').text(branch.BranchName).val(branch.BranchId));
                });
            });
        });

    });


</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EmployeeData/Views/EmployeeData/ListEmployee.cshtml
@model IEnumerable<EmployeeDAL.Employee>

@{
    ViewBag.Title = "ListEmployee";
}

<h2>List Of all employees</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
 <div class="div1"> <a href="@Url.Action("ExportToExcel", "EmployeeData")" class="export"><b>Export to Excel</b></a></div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmpId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmpName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Designation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegionId)
            @Html.DisplayNameFor(model => model.Region.RegionName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ZoneId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BranchId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Technology)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EmpId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmpName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Designation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Region.RegionName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zone.ZoneName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Branch.BranchName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Technology)
            </td>
            <td>
                <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#docModal_@item.EmpId">View Doc</a>
            </td>
        </tr>
    }

</table>

@foreach (var employee in Model)
{
    <div class="modal fade" id="docModal_@employee.EmpId" tabindex="-1" role="dialog" aria-labelledby="docModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="docModalLabel">Employee Documents</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    @if (employee.EmpDocuments.Any())
                    {
                        <ul>
                            @foreach (var doc in employee.EmpDocuments)
                            {
                                <li>
                                    @doc.DocName  <a href="@Url.Action("DownloadDoc", "EmployeeData", new { docId = doc.DocId })">Download</a>
                                                            </li>
                            }
                        </ul>
                    }
                    else
                    {
                        <p>No documents found.</p>
                    }
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        
        $(".div1").css("text-align","right",);
    });
</script>